export { default as SignUp } from './Day-1/SignUp';
export { default as CreditCardCheckout } from './Day-2/CreditCardCheckout';
export { default as LandingPage } from './Day-3/LandingPage';
export { default as Calculator } from './Day-4/Calculator';
// export { default as SignUp } from "./Day-1/SignUp";
export { default as UserProfile } from './Day-6/UserProfile';
export { default as Settings } from './Day-7/Settings';
export { default as ErrorPage404 } from './Day-8/ErrorPage404';
export { default as MusicPlayer } from './Day-9/MusicPlayer';
export { default as ShareScreen } from './Day-10/ShareScreen';
export { default as FlashMessage } from './Day-11/FlashMessage';
export { default as ECommerce } from './Day-12/ECommerce';
export { default as DirectMessaging } from './Day-13/DirectMessaging';
export { default as CountdownTimer } from './Day-14/CountdownTimer';
export { default as OnOffSwitch } from './Day-15/OnOffSwitch';
